server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6436/user
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.springframework.orm.jpa: ERROR
    org.springframework.transaction: ERROR