server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:

        # ---------------- USER SERVICE ----------------
        - id: user-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # ---------------- EVENT SERVICE ----------------
        - id: event-admin
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: event-user
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**

        - id: event-public
          uri: lb://event-service
          predicates:
            - Path=/events/**

        # ---------------- COMMENT SERVICE ----------------
        - id: comment-admin
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        - id: comment-user
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**

        # ---------------- REQUEST SERVICE ----------------
        - id: request-user
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**

        # ---------------- CATEGORY ----------------
        - id: category-admin
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**

        - id: category-public
          uri: lb://event-service
          predicates:
            - Path=/categories/**

        # ---------------- COMPILATIONS ----------------
        - id: compilation-admin
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: compilation-public
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        - id: stats-route
          uri: lb://stats-server
          predicates:
            - Path=/hit, /stats
